FROM luk/rpi-miniconda
MAINTAINER Lukasz Kuczynski <kuczynskilukasz@gmail.com>


RUN apt-get install unzip
RUN wget https://github.com/lukaszkuczynski/scout/archive/master.zip
RUN unzip master.zip
WORKDIR scout-master

RUN conda install pip
RUN pip install -r pip_requirements.txt
RUN conda install --yes --file conda_requirements.txt



RUN apt-get install mongodb-server

ENTRYPOINT service mongodb start && python web/web.py
